; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Acme Extensions"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "Acme Technology"
#define MyAppURL "http://www.acme.com/"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{03956A31-A2BB-4E48-8EFD-0C5E5DB8EBB8}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={pf32}\{#MyAppName}
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
OutputBaseFilename={#MyAppName} {#MyAppVersion}
Compression=lzma
SolidCompression=yes
UsePreviousAppDir=False
EnableDirDoesntExistWarning=True
DirExistsWarning=no
AppendDefaultDirName=False

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Types]
Name: "full"; Description: "Full installation"
Name: "custom"; Description: "Custom installation"; Flags: iscustom

[Components]
Name: "Feature1"; Description: "Feature 1"; Types: full custom;
Name: "Feature2"; Description: "Feature 2"; Types: full custom;
Name: "Feature3"; Description: "Feature 3"; Types: full custom;

[Files]
Source: "SharedComponent.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "Feature1.txt"; DestDir: "{app}"; Components: Feature1; Flags: ignoreversion
Source: "Feature2.txt"; DestDir: "{app}"; Components: Feature2; Flags: ignoreversion
Source: "Feature3.txt"; DestDir: "{app}"; Components: Feature3; Flags: ignoreversion



